export const COMPONENTS: { option: string; label: string; type: string }[] = [
  { option: 'intro', label: 'Introduction', type: 'introduction' },
  { option: 'changelog', label: 'Changelog', type: 'introduction' },
  { option: 'colors', label: 'Colors', type: 'styles' },
  { option: 'shadows', label: 'Shadows', type: 'styles' },
  { option: 'icons', label: 'Icons', type: 'icons' },
  { option: 'simple-grid', label: 'SimpleGrid', type: 'layout' },
  { option: 'heading', label: 'Heading', type: 'typography' },
  { option: 'menu', label: 'Menu', type: 'overlay' },
  { option: 'button', label: 'Button', type: 'form' },
  { option: 'icon-button', label: 'IconButton', type: 'form' },
  { option: 'radio', label: 'Radio', type: 'form' },
  { option: 'checkbox', label: 'Checkbox', type: 'form' },
  { option: 'switch', label: 'Switch', type: 'form' },
  { option: 'text-field', label: 'Text Field', type: 'form' },
  { option: 'select', label: 'Select', type: 'form' },
  { option: 'tag', label: 'Tag', type: 'data display' },
  { option: 'accordion', label: 'Accordion', type: 'disclosure' },
  { option: 'tabs', label: 'Tabs', type: 'disclosure' },
  { option: 'divider', label: 'Divider', type: 'data display' },
  { option: 'avatar', label: 'Avatar', type: 'data display' },
  { option: 'card', label: 'Card', type: 'data display' },
  { option: 'notice', label: 'Notice', type: 'feedback' },
  { option: 'time-picker', label: 'TimePicker', type: 'form' },
  { option: 'date-picker', label: 'DatePicker', type: 'form' },
  { option: 'description-list', label: 'DescriptionList', type: 'data display' },
  // { option: 'table', label: 'Table', type: 'data display' },
  { option: 'stepper', label: 'Stepper', type: 'form' },
  { option: 'demo1', label: 'Demo: Todo', type: 'demos' },
  { option: 'demo2', label: 'Demo: Issue', type: 'demos' },
];

export const LATEST = ['shadows', 'date-picker', 'menu'];
